src/main/java/org/wildfly/plugin/cli/ExecuteCommandsMojo.java
Contains support for skip parameter in execute-commands goal that enables to skip commands execution.
This parameter is available in other goals but it is missing in execute-commands goal.
=> Skip parameter for execute-commands goal

plugin/pom.xml
Executing `jms-queue add` command using current `master` (`1.1.0.Alpha3-SNAPSHOT`) version  causes an error:
A required class was missing while executing 
org.wildfly.plugins:wildfly-maven-plugin:1.1.0.Alpha3-SNAPSHOT:run: 
org/jboss/logmanager/LogContextSelector
Error call stack:
Caused by: java.lang.NoClassDefFoundError: org/jboss/logmanager/LogContextSelector
at org.jboss.as.cli.embedded.EmbeddedControllerHandlerRegistrar.registerEmbeddedCommands(EmbeddedControllerHandlerRegistrar.java:89)
at org.jboss.as.cli.impl.CommandContextImpl.initCommands(CommandContextImpl.java:484)
at org.jboss.as.cli.impl.CommandContextImpl.<init>(CommandContextImpl.java:283)
at org.jboss.as.cli.impl.CommandContextFactoryImpl.newCommandContext(CommandContextFactoryImpl.java:44)
at …
=> jms-queue command -> ClassNotFoundException: org.jboss.logmanager.LogContextSelector

plugin/src/main/java/org/wildfly/plugin/deployment/AbstractDeployment.java, plugin/src/main/java/org/wildfly/plugin/deployment/DeployArtifactMojo.java, plugin/src/main/java/org/wildfly/plugin/deployment/UndeployArtifactMojo.java, tests/standalone-tests/src/test/java/org/wildfly/plugin/deployment/ArtifactDeploymentTest.java
If the classifier of a project dependency is not defined it is null (maven 3.3.3).
This fix prevents a NPE during the verification of the mojo.
=> Prevent NPE if classifier of dependency is null

core/pom.xml, core/src/main/java/org/wildfly/plugin/core/Assertions.java, core/src/main/java/org/wildfly/plugin/core/DefaultDeploymentManager.java, core/src/main/java/org/wildfly/plugin/core/Deployment.java, core/src/main/java/org/wildfly/plugin/core/DeploymentContent.java, core/src/main/java/org/wildfly/plugin/core/DeploymentManager.java, core/src/main/java/org/wildfly/plugin/core/DeploymentOperations.java, core/src/main/java/org/wildfly/plugin/core/DeploymentResult.java, core/src/main/java/org/wildfly/plugin/core/ServerProcess.java, core/src/main/java/org/wildfly/plugin/core/SimpleDeploymentDescription.java, core/src/main/java/org/wildfly/plugin/core/UndeployDescription.java, core/src/test/java/org/wildfly/plugin/core/AbstractDeploymentManagerTest.java, core/src/test/java/org/wildfly/plugin/core/DeploymentResultTestCase.java, core/src/test/java/org/wildfly/plugin/core/DeploymentTestCase.java, core/src/test/java/org/wildfly/plugin/core/DomainDeploymentManagerIT.java, core/src/test/java/org/wildfly/plugin/core/Environment.java, core/src/test/java/org/wildfly/plugin/core/StandaloneDeploymentManagerIT.java, core/src/test/java/org/wildfly/plugin/core/common/Simple.java, plugin/src/main/java/org/wildfly/plugin/deployment/MavenDeployment.java, pom.xml, tests/domain-tests/src/test/java/org/wildfly/plugin/deployment/UndeploymentMatchTest.java, tests/domain-tests/src/test/java/org/wildfly/plugin/server/DomainTestServer.java, tests/pom.xml, tests/shared/src/main/java/org/wildfly/plugin/server/TestServer.java, tests/standalone-tests/src/test/java/org/wildfly/plugin/server/StandaloneTestServer.java
@jmazzitelli Just an FYI I've changed the result of the `DeploymentResult.asModelNode()` if you're using it at all. Before it returned just the result portion of the response, `Operations.readResult(result)`. Now it returns the original response so if you're using that method you might need to make some changes.
Basically before you would have gotten
```
{
"step-1" => {"outcome" => "success"},
"step-2" => {"outcome" => "success"}
}
```
Now you'll get the full response
```
{
"outcome" => "success",
"result" => {
"step-1" => {"outcome" => "success"},
"step-2" => {"outcome" => "success"}
}
}
```
=> [WFMP-47] Add tests for core module

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java, plugin/src/main/java/org/wildfly/plugin/deployment/AbstractDeployment.java, plugin/src/main/java/org/wildfly/plugin/deployment/DeployOnlyMojo.java, plugin/src/main/java/org/wildfly/plugin/deployment/RedeployMojo.java, plugin/src/main/java/org/wildfly/plugin/deployment/RedeployOnlyMojo.java, tests/standalone-tests/src/test/java/org/wildfly/plugin/deployment/DeployOnlyTest.java
This allows content in a remote repository to be deployed.
Also a commit to validate that a deployment exists before an attempt is made to redploy it.
=> [WFMP-9] Add a URL parameter to the deploy-only and redploy-only goals. 

plugin/src/main/java/org/wildfly/plugin/server/ModulesPath.java
See [WFMP-84](https://issues.jboss.org/browse/WFMP-84) for further explanation.
=> WFMP-84 fix NPE when using path-elements for modulesPath

.github/workflows/ci.yml, plugin/src/main/java/org/wildfly/plugin/cli/ExecuteCommandsMojo.java, plugin/src/main/java/org/wildfly/plugin/server/RunMojo.java, plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java, plugin/src/site/fml/faq.fml, pom.xml
https://issues.redhat.com/browse/WFMP-130
Also https://issues.redhat.com/browse/WFMP-132
=> [WFMP-130] Deprecate parameters that refer to downloading a Maven artifact for the server. These will be removed in 3.0.0.

core/src/main/java/org/wildfly/plugin/core/ServerHelper.java, core/src/main/java/org/wildfly/plugin/core/Utils.java, plugin/src/main/java/org/wildfly/plugin/cli/AbstractCommandExecutor.java, plugin/src/main/java/org/wildfly/plugin/cli/BaseCommandConfiguration.java, plugin/src/main/java/org/wildfly/plugin/cli/CommandConfiguration.java, plugin/src/main/java/org/wildfly/plugin/cli/CommandExecutor.java, plugin/src/main/java/org/wildfly/plugin/cli/ExecuteCommandsMojo.java, plugin/src/main/java/org/wildfly/plugin/cli/OfflineCommandExecutor.java, plugin/src/main/java/org/wildfly/plugin/cli/ScriptWriter.java, plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java, plugin/src/main/java/org/wildfly/plugin/server/RunMojo.java
* Introduce a BaseCommandConfiguration CLI configuration class and builder.
* Refactor CommandConfiguration to inherit from BaseCommandConfiguration and expose builder.
* Introduce an AbstractCommandExecutor.
* Refactor the CommandExecutor to inherit from the AbstractCommandExecutor
* Introduce an OfflineCommandExecutor to inherit from the AbstractCommandExecutor.
* OfflineCommandExecutor is injected into the package goal
* CommandExecutor is injected into other goals (unchanged).
=> Fix for WFMP-145, Introduce an offline CLI command executor

plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
Issues:
https://issues.redhat.com/browse/WFWIP-439
https://issues.redhat.com/browse/WFWIP-440
=> Fix for WFWIP-439 and WFWIP-440, provisioning-dir can be set to absolute path, '.' and outside target dir

core/src/main/java/org/wildfly/plugin/core/GalleonUtils.java, plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java, plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
Issue: https://issues.redhat.com/browse/WFMP-146
Introduce new configuration item to provide a name for the generated config (default being standalone.xml).
=> Fix for WFMP-146, Add the ability to provide a name for layers based configuration

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
Issue: https://issues.redhat.com/browse/WFWIP-460
=> Fix for WFWIP-460, When extra-content-dir is a regular file, build process fails without explanation

pom.xml
That will be required as soon as https://github.com/wildfly/wildfly/pull/15827 is in.
=> Fix for WFMP-170, Must upgrade to Galleon 5.0.5.Final

plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageInfo.java, plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/ExecUtil.java, plugin/src/site/markdown/image-example.md.vm, plugin/src/site/markdown/index.md.vm, plugin/src/site/site.xml, tests/standalone-tests/src/test/java/org/wildfly/plugin/provision/ImageTest.java, tests/standalone-tests/src/test/resources/test-project/image-pom.xml, tests/standalone-tests/src/test/resources/test-project/image-unknown-docker-binary-pom.xml
As an user, I want to build and push an application image from the plugin
https://issues.redhat.com/browse/WFMP-174
=> [WFMP-174] New image goal to build (and push) application image

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java, plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
If wildfly.package.deployment.skip is true, the user deployment will not be deployed in the provisioned server.
JIRA: https://issues.redhat.com/browse/WFMP-175
=> [WFMP-175] Add property to skip the deployment in the package goal.

plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageMojo.java
Why the pull request?
We're currently using the wildfly plugin from a child pom. When we call the child pom from the parent pom, the plugin wants to push the image from the directory <parent_pom>/target, which does not exist. Only the directory <child_pom>/target exists. Generating and building the docker file all happens from the project build directory as well, so hopefully this makes sense.
=> Push image from project build directory path instead of hard target path

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
Skiping the deployment using a system property won't work since it uses the skip.package name
=> Wrong system property name to skip deployment

core/pom.xml, pom.xml
* Dependencies have been reworked in Galleon
* Add previous transitive dep as dependency.
=> Upgrade to galleon 5.0.7.Final

plugin/pom.xml, plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java, plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java, pom.xml
Issues: 
* https://issues.redhat.com/browse/WFMP-177
* https://issues.redhat.com/browse/WFMP-178
* Latest changes introduced in wildfly-channel 1.0.0.Beta4
* Use prospero project to generate metadata file when channels are setup.
=> WFMP-177 and WFMP-178

plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageInfo.java, plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageMojo.java
Use the new naming convention for the WildFly runtime image. They all have the same name, `quay.io/wildfly/wildfly-runtime` and uses tags to specify the JDK version.
By default, `jdkVersion` is no longer set so that the WildFLy runtime image will use its latest tag by default. This tag corresponds to the most recent LTS JDK version provided by WildFly (11 at the moment, eventually 17, etc).
User can stay on a specify JDK version by setting <jdk-version> to 11 or 17.
JIRA: https://issues.redhat.com/browse/WFMP-182
=> [WFMP-182] Update WildFly runtime image names

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java, tests/shared/src/main/java/org/wildfly/plugin/tests/AbstractProvisionConfiguredMojoTestCase.java
Instead of using the `deploy` management operation, the deployment is copied into the standalone/deployments directory.
The runtime-name field is now used to rename the file that is copied to the standalone/deployments directory.
JIRA: https://issues.redhat.com/browse/WFMP-185
=> [WFMP-185] Deploy the application by copying it to deployments dir

plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java, tests/standalone-tests/src/test/resources/test-project/image-pom.xml
In the image goal, skip the deployment when packaging WildFly
In the generated Dockerfile, use 2 different COPY commands:
* COPY the server bits. This Docker layer can be cached (as long as the server provisioning does not change)
* COPY the deployment in the standalone/deployment directory. This Docker layer is small (the size of the deployment) and will be changed every time
With that optimization, repeatedly pushing the application image will mean to push the deployment Docker layer only.
This optimization saves time, bandwith and storage on the container registry.
JIRA: https://issues.redhat.com/browse/WFMP-186
=> [WFMP-186] Optimize the application image generated by the image goal

plugin/pom.xml, plugin/src/main/java/org/wildfly/plugin/common/Environment.java, plugin/src/main/java/org/wildfly/plugin/common/Utils.java, plugin/src/main/java/org/wildfly/plugin/dev/CompiledSourceHandler.java, plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java, plugin/src/main/java/org/wildfly/plugin/dev/ResourceHandler.java, plugin/src/main/java/org/wildfly/plugin/dev/WatchContext.java, plugin/src/main/java/org/wildfly/plugin/dev/WatchHandler.java, plugin/src/main/java/org/wildfly/plugin/dev/WebAppResourceHandler.java, plugin/src/main/java/org/wildfly/plugin/server/AbstractServerStartMojo.java, plugin/src/main/java/org/wildfly/plugin/server/RunMojo.java, plugin/src/main/java/org/wildfly/plugin/server/ServerContext.java, plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java, plugin/src/site/markdown/dev-example.md.vm, plugin/src/site/markdown/index.md.vm, plugin/src/site/markdown/usage.md.vm, plugin/src/site/site.xml, pom.xml
https://issues.redhat.com/browse/WFMP-191
@jmesnil @jfdenise What do you guys think of something like this? This isn't yet complete, but it's been something I've wanted to do for a long time. It would differ a bit from the bootable-jar `dev-watch` goal in that we just need to build the WAR and possibly redeploy it.
There are currently some issues with IDE's like IDEA which aggressively save and it keeps trying to compile invalid sources. I'm not completely sure how to handle that. One idea I had was to keep a queue of changed files and only compile when a compile is not already happening. Maybe using a timer of some sort. I've not looked to see how the bootable JAR plugin handles this.
Anyway, just looking for some feedback on the idea.
=> [WFMP-191] Add a dev goal for rapid development of WAR files.

plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java, pom.xml
Issue: https://issues.redhat.com/browse/WFMP-194
Requires https://github.com/wildfly-extras/prospero/pull/318 and prospro-metadata update
=> [WFMP-194] Record versions of manifests used to provision server

plugin/src/site/markdown/index.md.vm
https://issues.redhat.com/browse/WFMP-193
I was not able to update the "provisioningDir configuration parameter marked as since 3.0" as it would require either removing the `@since` or overriding the property which would add complications. It's doesn't feel like too big of a deal to just deal with it.
=> [WFMP-193] Add the dev goal to the index.

plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java, pom.xml
Issue: https://issues.redhat.com/browse/WFMP-207
Note: requires [wildfly-channel](https://github.com/wildfly-extras/wildfly-channel/pull/179) - I'll update the PR when a new version is released
cc @jfdenise
=> [WFMP-207] Do not perform artifact resolution fallback if the channel resolution failed due to transfer error

plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java
* Adding a new 'name' parameter with the same property as for the package mojo.
Jira: https://issues.redhat.com/browse/WFMP-208
=> [WFMP-208]: dev mode deployment runtime name is not configurable.

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java, plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java, plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java
https://issues.redhat.com/browse/WFMP-225
=> [WFMP-225] Add a property for the channels configuration parameter.

plugin/src/main/java/org/wildfly/plugin/common/Utils.java, plugin/src/main/java/org/wildfly/plugin/provision/GlowConfig.java
Issue: https://issues.redhat.com/browse/WFMP-236
=> Fix for WFMP-236, The generated configuration name is not used when WildFly Glow is enabled

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java, plugin/src/main/java/org/wildfly/plugin/server/AbstractServerStartMojo.java, plugin/src/main/java/org/wildfly/plugin/server/AbstractStartMojo.java, plugin/src/main/java/org/wildfly/plugin/server/StartJarMojo.java
Issue: https://issues.redhat.com/browse/WFMP-235
=> Fix for WFMP-235, Introduce a start-jar goal

plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java, plugin/src/test/java/org/wildfly/plugin/provision/ChannelConfigurationTestCase.java
I find it impossible to reference a local manifest file.
When I use "file://path/to/manifest.yaml", I get:
```
Caused by: java.net.UnknownHostException: wildfly-ee-galleon-pack-32.0.0.Beta1-SNAPSHOT-manifest.yaml
at sun.nio.ch.NioSocketImpl.connect (NioSocketImpl.java:572)
at java.net.Socket.connect (Socket.java:633)
at sun.net.ftp.impl.FtpClient.doConnect (FtpClient.java:1045)
at sun.net.ftp.impl.FtpClient.tryConnect (FtpClient.java:1010)
at sun.net.ftp.impl.FtpClient.connect (FtpClient.java:1102)
at sun.net.ftp.impl.FtpClient.connect (FtpClient.java:1088)
at sun.net.www.protocol.ftp.FtpURLConnection.connect (FtpURLConnection.java:320)
at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream (FtpURLConnection.java:426)
at java.net.URL.openStream (URL.java:1161)
at …
```
=> Allow the "file:relative/path" URL notation for manifest coordinate

pom.xml
This came up while looking into updating jboss-logging in wildfly-core. See https://github.com/wildfly/wildfly-core/pull/6058#discussion_r1670686892
=> [WFMP-264] Bump version.org.jboss.logging.jboss-logging from 3.5.3.Final to 3.6.0.Final

plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java
to be able to name the channels that are
used to provision the server and keep the information in the .instatallation directory of the server for future updates.
JIRA: https://issues.redhat.com/browse/WFMP-271
=> [WFMP-271] Add name field to the ChannelConfiguration

plugin/src/main/java/org/wildfly/plugin/common/Utils.java, plugin/src/main/java/org/wildfly/plugin/provision/GlowConfig.java, plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java, tests/standalone-tests/src/test/java/org/wildfly/plugin/provision/PackageTest.java, tests/standalone-tests/src/test/resources/test-project/package-glow-no-deployment-pom.xml
Issue: https://issues.redhat.com/browse/WFMP-266
=> Fix for WFMP-266, Allow to configure glow discovery to not scan the deployment

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java, plugin/src/site/markdown/package-example.md.vm
Issue: https://issues.redhat.com/browse/WFMP-270
In addition, added documentation on how to produce a bootable JAR.
=> Fix for WFMP-270, Plugin description should specify how to build a Hollow JAR

plugin/src/main/java/org/wildfly/plugin/common/Utils.java
Issue: https://issues.redhat.com/browse/WFMP-277
Reported by: https://github.com/wildfly/wildfly-maven-plugin/discussions/580
=> Fix for WFMP-277, Exception when discover-provisioning-info and feature-packs are set

pom.xml, tests/bootable-tests/src/test/java/org/wildfly/plugin/bootable/PackageBootableTest.java, tests/bootable-tests/src/test/resources/test-project/package-bootable-pom.xml, tests/standalone-tests/src/test/resources/test-project/package-invalid-deployment-pom.xml, tests/standalone-tests/src/test/resources/test-project/package-invalid-deployment2-pom.xml
@jfdenise requested to open this upstream PR too.
Both slf4j-api and commons-lang3 transitive deps will still be present,
but in different versions that better suit us. This makes it easier to
perform automatic dependency alignments.
=> Repeatable teststuite, exluding wrong versions of slf4j-api & commons-lang3

plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java, pom.xml
This is the prospero-metadata version minor relevant to next EAP stream.
=> Upgrade prospero-metadata to 1.3.0.Beta2

pom.xml
This upgrade makes WildFly Glow to retrieve its metadata from maven, that is something that blocks some users to use the WildFly Maven Plugin with Glow feature (in some pipeline context where only maven repositories are allowed to connect to).
=> Fix for WFMP-290, Upgrade to Glow 1.3.0.Final
