wildfly/wildfly-maven-plugin

src/main/java/org/wildfly/plugin/server/ShutdownMojo.java
src/main/java/org/wildfly/plugin/server/StartMojo.java

Fixes #26 The plugin cannot skip start and shutdown

Fixes #26 The plugin cannot skip start and shutdown

---

plugin/src/main/java/org/wildfly/plugin/cli/CommandExecutor.java
plugin/src/main/java/org/wildfly/plugin/cli/Commands.java

In the process, I removed some spurious throws clauses and converted some return types from Collection to List (because a List is ordered).

Add support for properties files, like the CLI client does.

---

plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java

this works for me, if you would like to rework it, drop it ;)

Issue #130: fixed start if already running an instance?

---

core/pom.xml
core/src/main/java/org/wildfly/plugin/core/ServerHelper.java

https://issues.jboss.org/browse/WFMP-83

[WFMP-83] Remove the wildfly-launcher runtime dependency.

---

pom.xml

https://issues.jboss.org/browse/WFMP-99

[WFMP-99] Upgrade WildFly Core to 6.0.2.Final.

---

core/src/main/java/org/wildfly/plugin/core/ServerHelper.java
core/src/test/java/org/wildfly/plugin/core/DomainDeploymentManagerIT.java
plugin/src/main/java/org/wildfly/plugin/cli/OfflineCLIExecutor.java
plugin/src/main/java/org/wildfly/plugin/common/AbstractServerConnection.java
plugin/src/main/java/org/wildfly/plugin/common/Environment.java
plugin/src/main/java/org/wildfly/plugin/server/AddUser.java
plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java
pom.xml
tests/domain-tests/src/test/java/org/wildfly/plugin/server/DomainTestServer.java
tests/shared/src/main/java/org/wildfly/plugin/tests/AbstractWildFlyMojoTest.java
tests/shared/src/main/java/org/wildfly/plugin/tests/TestEnvironment.java
tests/shared/src/test/java/org/wildfly/plugin/server/ServerFunctionMojoTest.java
tests/standalone-tests/src/test/java/org/wildfly/plugin/cli/ExecuteCommandsTest.java
tests/standalone-tests/src/test/java/org/wildfly/plugin/cli/FailOnErrorTest.java
tests/standalone-tests/src/test/java/org/wildfly/plugin/server/StandaloneTestServer.java

https://issues.jboss.org/browse/WFMP-100

Component upgrades and ensure plugin works with Java 9+

---

pom.xml

https://issues.jboss.org/browse/WFMP-101

[WFMP-101] Upgrade jboss-parent from 26 to 29

---

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/server/RunMojo.java
plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java
plugin/src/site/fml/faq.fml

https://issues.jboss.org/browse/WFMP-107

[WFMP-107] Remove deprecated jvm-args in favor java-opts.

---

pom.xml

https://issues.jboss.org/browse/WFMP-108

[WFMP-108] Use WildFly 14.0.1.Final for testing.

---

plugin/src/main/java/org/wildfly/plugin/deployment/resource/Resource.java
plugin/src/site/fml/faq.fml

https://issues.jboss.org/browse/WFMP-109

[WFMP-109] Deprecate the beforeAdd and afterAdd configuration options.

---

pom.xml

https://issues.jboss.org/browse/WFMP-113

[WFMP-113] Upgrade commons-compress from 1.16.1 to 1.18.

---

plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java

https://issues.jboss.org/browse/WFMP-114

WFMP-114 Added Modular Jvm Arguments to standalone and process controller

---

plugin/pom.xml
pom.xml

https://issues.jboss.org/browse/WFMP-121

[WFMP-121] Remove the jboss-modules dependency.

---

pom.xml

https://issues.jboss.org/browse/WFMP-123

[WFMP-123] Upgrade commons-compress from 1.18 to 1.19

---

plugin/src/main/java/org/wildfly/plugin/cli/ExecuteCommandsMojo.java

https://issues.redhat.com/browse/WFMP-125

[WFMP-125] Ensure the connection timeout gets set for the CLI process.

---

.github/workflows/ci.yml
pom.xml

- https://issues.redhat.com/browse/WFMP-133
- https://issues.redhat.com/browse/WFMP-134
- https://issues.redhat.com/browse/WFMP-135
- https://issues.redhat.com/browse/WFMP-136
- https://issues.redhat.com/browse/WFMP-137

Component upgrades and testing on Java 17.

---

plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
tests/shared/pom.xml

These changes could be needed by other plugin depending on wildfly-maven-plugin plugin and testing.

Make repositories enrichment a method - Tests shared module is deployed

---

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java

Issue: https://issues.redhat.com/browse/WFMP-141
Add the ability to do deployment and disabling re-packaging of the server: mvn wildfly:deploy -Dwildfly.package.skip

Fix for WFMP-141, Can't deploy without packaging

---

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
tests/standalone-tests/src/test/java/org/wildfly/plugin/provision/PackageTest.java
tests/standalone-tests/src/test/resources/test-project/package-invalid-deployment-pom.xml
tests/standalone-tests/src/test/resources/test-project/package-invalid-deployment2-pom.xml
tests/standalone-tests/src/test/resources/test-project/package-no-deployment-pom.xml

Issue: https://issues.redhat.com/browse/WFMP-142

Fix for WFMP-142, Plugin should handle the case of not found deployment

---

plugin/src/main/java/org/wildfly/plugin/cli/ExecuteCommandsMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/ProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/server/RunMojo.java
plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java

Signed-off-by: James R. Perkins <jperkins@redhat.com>

Add @since annotation where applicable for 3.0.

---

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java

Issue: https://issues.redhat.com/browse/WFWIP-444

Fix for WFWIP-444, Typo in wildfly-maven-plugin model description

---

core/pom.xml
core/src/main/java/org/wildfly/plugin/core/ConfigurationId.java
core/src/main/java/org/wildfly/plugin/core/FeaturePack.java
core/src/main/java/org/wildfly/plugin/core/GalleonUtils.java
plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
pom.xml

Issue: https://issues.redhat.com/browse/WFMP-148

Fix for WFMP-148, Support for iterative development workflow

---

plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java

Issue: https://issues.redhat.com/browse/WFWIP-451

Fix for WFWIP-451, NPE when using packaging script with null script path

---

.github/workflows/ci.yml
core/pom.xml
plugin/pom.xml
pom.xml
tests/domain-tests/pom.xml
tests/pom.xml
tests/shared/pom.xml
tests/standalone-tests/pom.xml

https://issues.redhat.com/browse/WFMP-155
Related to #228

Require Java 11 and update version

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFMP-156
---
Dev tag: https://github.com/wildfly/galleon/releases/tag/5.0.1.Final
Diff to current integrated version: https://github.com/wildfly/galleon/compare/4.2.8.Final...5.0.1.Final

[WFMP-156] Upgrade galleon-maven-plugin to 5.0.1.Final

---

core/src/main/java/org/wildfly/plugin/core/GalleonUtils.java
plugin/pom.xml
plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
pom.xml

JIRA: https://issues.redhat.com/browse/WFMP-154

[WFMP-154] Integrate Channels to provision WildFly

---

plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
pom.xml

JIRA: https://issues.redhat.com/browse/WFMP-157

[WFMP-157] Upgrade wildfly-channel 1.0.0.Alpha14

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFMP-159
---
Dev tag: https://github.com/wildfly-extras/wildfly-channel/releases/tag/1.0.0.Alpha16
Diff to previous integrated release: https://github.com/wildfly-extras/wildfly-channel/compare/1.0.0.Alpha14...1.0.0.Alpha16

[WFMP-159] Upgrade wildfly-channel 1.0.0.Alpha16

---

pom.xml

JIRA: https://issues.redhat.com/browse/WFMP-168
---
Dev tag: https://github.com/wildfly-extras/wildfly-channel/releases/tag/1.0.0.Beta2
Diff to previous integrated release: https://github.com/wildfly-extras/wildfly-channel/compare/1.0.0.Beta1...1.0.0.Beta2
---

[WFMP-168] Upgrade wildfly-channel 1.0.0.Beta2

---

.github/dependabot.yml
pom.xml

Several component upgrades and enable dependabot.

Component upgrades

---

.github/workflows/ci.yml

Signed-off-by: James R. Perkins <jperkins@redhat.com>

Ignore extra runs for dependabot PR's

---

plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java
plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
plugin/src/test/java/org/wildfly/plugin/provision/ChannelConfigurationTestCase.java

Issue: https://issues.redhat.com/browse/WFMP-184

Fix for WFMP-184, Rework Channel configuration

---

plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/PluginProgressTracker.java

Issue: https://issues.redhat.com/browse/WFMP-190

Fix for WFMP-190, Improve progress tracking during provisioning

---

pom.xml

Git tag + release notes:
https://github.com/wildfly-extras/wildfly-channel/releases/tag/1.0.0.Beta5
JIRA: https://issues.redhat.com/browse/WFMP-187

[WFMP-187] Upgrade WildFly Channel 1.0.0.Beta5

---

plugin/src/site/markdown/index.md.vm
plugin/src/site/site.xml
pom.xml

https://issues.redhat.com/browse/WFMP-179

[WFMP-179] Fix dead links and update the JIRA link.

---

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java

Issue: https://issues.redhat.com/browse/WFMP-195

Fix for WFMP-195, Fallback behavior when channels are configured is incorrect

---

plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java
plugin/src/main/java/org/wildfly/plugin/server/AbstractServerStartMojo.java

https://issues.redhat.com/browse/WFMP-196

[WFMP-196] Allow the dev goal to work on remote servers.

---

.github/workflows/ci.yml

instead of WildFly 27.0.0.Final.

Use WildFly 27.0.1.Final for verification

---

plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/ChannelMavenArtifactRepositoryManager.java
pom.xml

Issue: https://issues.redhat.com/browse/WFMP-200

Fix for WFMP-200, Dynamic artifact resolution fallback when using WildFly channels

---

core/src/main/java/org/wildfly/plugin/core/Deployment.java
core/src/main/java/org/wildfly/plugin/core/DeploymentContent.java

https://issues.redhat.com/browse/WFMP-213

[WFMP-213] Add option to allow local archived deployments.

---

plugin/pom.xml
pom.xml
tests/domain-tests/pom.xml
tests/standalone-tests/pom.xml

https://issues.redhat.com/browse/WFMP-216

[WFMP-216] Remove the jboss-logmanager dependency.

---

.github/dependabot.yml
pom.xml

This seems to work with older versions of Maven. I tested locally with 3.6.3 so we may as well upgrade.

Upgrade Maven dependencies.

---

.github/workflows/static-site.yml
plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/GlowConfig.java
plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java

Update the site action to only execute if the docs directory is updated.
Some minor formatting/style updates.

Minor cleanup and fixes

---

plugin/pom.xml

https://issues.redhat.com/browse/WFMP-217

[WFMP-217] Require a minimum of Maven 3.6.3.

---

pom.xml

[4.1] Update prospero and wildfly-channels versions

---

.github/workflows/legacy-build.yml
pom.xml
tests/standalone-tests/src/test/java/org/wildfly/plugin/provision/ImageTest.java

[4.2] Update CI to run less jobs and cleaner

---

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java

https://issues.redhat.com/browse/WFMP-225
Upstream #417

[WFMP-225] Add a property for the channels configuration parameter.

---

core/src/main/java/org/wildfly/plugin/core/ConfigurationId.java
core/src/main/java/org/wildfly/plugin/core/ConsoleConsumer.java
core/src/main/java/org/wildfly/plugin/core/ContainerDescription.java
core/src/main/java/org/wildfly/plugin/core/DefaultContainerDescription.java
core/src/main/java/org/wildfly/plugin/core/DefaultDeploymentManager.java
core/src/main/java/org/wildfly/plugin/core/Deployment.java
core/src/main/java/org/wildfly/plugin/core/DeploymentContent.java
core/src/main/java/org/wildfly/plugin/core/DeploymentDescription.java
core/src/main/java/org/wildfly/plugin/core/DeploymentException.java
core/src/main/java/org/wildfly/plugin/core/DeploymentManager.java
core/src/main/java/org/wildfly/plugin/core/DeploymentOperations.java
core/src/main/java/org/wildfly/plugin/core/DeploymentResult.java
core/src/main/java/org/wildfly/plugin/core/FeaturePack.java
core/src/main/java/org/wildfly/plugin/core/GalleonUtils.java
core/src/main/java/org/wildfly/plugin/core/OperationExecutionException.java
core/src/main/java/org/wildfly/plugin/core/PluginProgressTracker.java
core/src/main/java/org/wildfly/plugin/core/ServerHelper.java
core/src/main/java/org/wildfly/plugin/core/SimpleDeploymentDescription.java
core/src/main/java/org/wildfly/plugin/core/UndeployDescription.java
core/src/main/java/org/wildfly/plugin/core/Utils.java

https://issues.redhat.com/browse/WFMP-231
Removal PR #447

[WFMP-231] Deprecate the API's removed and moved in 5.0.x.

---

.github/workflows/static-site.yml

Reverts wildfly/wildfly-maven-plugin#451

Revert "Bump actions/deploy-pages from 3 to 4"

---

.github/workflows/static-site.yml

Reverts wildfly/wildfly-maven-plugin#452

Revert "Bump actions/upload-pages-artifact from 2 to 3"

---

plugin/src/main/java/org/wildfly/plugin/provision/GlowConfig.java
plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
pom.xml

Issue: https://issues.redhat.com/browse/WFMP-237

Fix for WFMP-237, verbose argument when discovering provisioning info

---

pom.xml

https://issues.redhat.com/browse/WFMP-238

[WFMP-238] Upgrade wildfly-plugin-tools to 1.0.0.Beta2

---

pom.xml

Issue: https://issues.redhat.com/browse/WFMP-240

Fix for WFMP-240, Upgrade to WildFly Glow 1.0.0.Beta5

---

plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java
plugin/src/test/java/org/wildfly/plugin/provision/ChannelConfigurationTestCase.java

Issue: https://issues.redhat.com/browse/WFMP-245

Fix for WFMP-245, Confusing error message when not specifying manifest as individual channel

---

plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java
plugin/src/test/java/org/wildfly/plugin/provision/ChannelConfigurationTestCase.java

Issue: https://issues.redhat.com/browse/WFMP-245

[4.1] Fix for WFMP-245, Confusing error message when not specifying manifest as individual channel

---

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/main/java/org/wildfly/plugin/provision/ChannelConfiguration.java
plugin/src/test/java/org/wildfly/plugin/provision/ChannelConfigurationTestCase.java
tests/standalone-tests/src/test/java/org/wildfly/plugin/provision/ImageTest.java

https://issues.redhat.com/browse/WFMP-253
https://issues.redhat.com/browse/WFMP-225

WFMP-225 WFMP-253: Backport configuration via the wildfly.channels system property to 4.1

---

core/pom.xml

Issue: https://issues.redhat.com/browse/WFMP-254

Fix for WFMP-254, Dependency on maven-core should be provided

---

plugin/src/site/markdown/package-example.md.vm

Issue: https://issues.redhat.com/browse/WFMP-255

Fix for WFMP-255, Fix Galleon Options code snippet

---

plugin/src/main/java/org/wildfly/plugin/provision/AbstractProvisionServerMojo.java
plugin/src/site/markdown/channel-example.md.vm
plugin/src/site/markdown/index.md.vm
plugin/src/site/markdown/package-example.md.vm
plugin/src/site/markdown/provision-example.md.vm
plugin/src/site/site.xml
pom.xml
tests/bootable-tests/pom.xml
tests/pom.xml

https://issues.redhat.com/browse/WFMP-248

Various docs updates, upgrade WildFly to 32 and using the plugin itself for provisioning the test servers

---

plugin/src/main/java/org/wildfly/plugin/common/PropertyNames.java
plugin/src/main/java/org/wildfly/plugin/provision/ApplicationImageMojo.java
tests/standalone-tests/src/test/java/org/wildfly/plugin/provision/ImageTest.java
tests/standalone-tests/src/test/resources/test-project/image-pom.xml

https://issues.redhat.com/browse/WFMP-262
replaces #543

[WFMP-262]: Allow to add labels to the images.

---

plugin/pom.xml
pom.xml
tests/bootable-tests/pom.xml
tests/domain-tests/pom.xml
tests/shared/pom.xml
tests/standalone-tests/pom.xml

A trivial replacement of groupId for artifacts defined in this project.

Replace some hardcoded groupId with project property

---

plugin/pom.xml
pom.xml

https://issues.redhat.com/browse/WFMP-280

[WFMP-280] Migrate to the new WildFly Launcher API GAV.

---

plugin/src/main/java/org/wildfly/plugin/provision/GlowConfig.java
plugin/src/main/java/org/wildfly/plugin/provision/PackageServerMojo.java
pom.xml

Issue: https://issues.redhat.com/browse/WFMP-282

Fix for WFMP-282, Allow to set spaces in the Glow configuration

---

pom.xml

This is just a micro upgrade to sync with prospero.

Upgrade org.apache.maven:maven-core to 3.9.9

---

pom.xml

https://issues.redhat.com/browse/WFMP-287

[WFMP-287] Upgrade WildFly GLOW to 1.2.0.Final.

---

plugin/src/main/java/org/wildfly/plugin/dev/DevMojo.java

https://issues.redhat.com/browse/WFMP-305

[WFMP-305] Ensure a server is provisioned if WildFly Glow is enabled.
